### PR TITLE
Search autocomplete. closes #121, closes #127

### LINKED ISSUE #121: Update the search box text to include "search terms" + update screenshot
With #120, we have support for proper search just as you'd do on YouTube!

The placeholder text should become something like

    Search, YouTube video ID, or URL

### LINKED ISSUE #127: Search autocomplete
Youtube's search bar gives query suggestions as you type.

unspecified

### PR DESCRIPTION
**Pull request by monicacheung**
Added typeahead.js library.
Updated the input field placeholder and added search autocomplete.

typeahead.js conflicts with primercss, so there are some css workarounds.

Closes #121, closes #127

### CODE REVIEW

**Comment by monicacheung** [comment]
```
css/styles.css
31:3	Unexpected vendor-prefixed selector "::-webkit-input-placeholder" (selector-no-vendor-prefix)
34:3	Unexpected vendor-prefixed selector ":-moz-placeholder" (selector-no-vendor-prefix)
37:3	Unexpected vendor-prefixed selector "::-moz-placeholder" (selector-no-vendor-prefix)
37:4	Unexpected vendor-prefixed selector ":-moz-placeholder" (selector-no-vendor-prefix)
40:3	Unexpected vendor-prefixed selector ":-ms-input-placeholder" (selector-no-vendor-prefix)
91:21	Unexpected !important (declaration-no-important)
100:21	Unexpected !important (declaration-no-important)
```

Trying to resolve the stylelint errors. The "vendor-prefixed selector" just center the placeholder text in the input field. Centering the placeholder is optional and can be removed. But the css with ```!important``` are unavoidable and necessary to make the input field and hint color to look right ...

**Comment by monicacheung** [comment]
Fixed the lint errs..

**Comment by agauniyal** [comment]
Isn't bower something like npm? Should we be adding each and every file to this repo and why even use bower if it isn't pulling packages/files while updating eg as we do in npm update.

**Comment by shakeelmohamed** [comment]
Thanks @monicacheung I will take a look at the changes.

@agauniyal That's a very valid question. The reason we check in the bower dependencies is that the website is hosted with GitHub pages. That means it's a static site, and there is no "deployment" process like you might have with Heroku. GitHub pages are the equivalent of copying the repository to a web server, so `bower install` doesn't get run on the server at any point. We're using bower to keep things organized. If you want to continue this discussion, let's open a new issue or message me on gitter. I hope that makes sense :smile:

**Comment by agauniyal** [comment]
ah okay! I totally forgot about the fact that we're using github pages. :+1:

**Comment by shakeelmohamed** [comment]
@monicacheung this looks like a very good start, we're almost there actually!

Here's a few style changes I'd like to see, the diff is below

capturfiles_19


```diff
diff --git a/css/styles.css b/css/styles.css
index a356757..a9bc3a3 100644
--- a/css/styles.css
+++ b/css/styles.css
@@ -26,6 +26,7 @@ header, footer {
 #v {
     margin: 0 auto;
     width: 100%;
+    text-align: center;
 }
 
 #player {
@@ -85,7 +86,7 @@ header, footer {
 }
 
 .twitter-typeahead .tt-hint {
-    color: #c1c1c1;
+    display: none;
 }
 
 .tt-menu {
@@ -96,8 +97,8 @@ header, footer {
 }
 
 .tt-suggestion {
-    padding: 0 8px;
     font-weight: bold;
+    text-align: center;
 }
 
 .tt-suggestion strong {
```

Can you investigate what we need to do for highlighting autocomplete results when using keyboard up/down? The following from their [examples](http://twitter.github.io/typeahead.js/examples/) page has this feature, and it would improve keyboard navigability
capturfiles_14

Some additional TODOs:

- [ ] Test on MS Edge
- [ ] Update the screenshot

**Comment by monicacheung** [comment]
@shakeelmohamed Sure, I'll get the changes in this evening.

**Comment by shakeelmohamed** [comment]
LGTM - the UI isn't perfect on Edge, but it's good enough!
Let's update the screenshot and merge it in :fireworks:

**Comment by monicacheung** [comment]
Updated the screenshot. What does it look like on Edge?

**Comment by shakeelmohamed** [comment]
@monicacheung Thanks for doing this! On edge I noticed an X at the right of the textbox which appears to be a browser feature to clear the input. I have a screenshot somewhere :smile:

**Comment by shakeelmohamed** [comment]
FYI @monicacheung, here's a screenshot on Edge
capturfiles_4

**Comment by monicacheung** [comment]
@shakeelmohamed  Oh, you can raise an issue for this. Should be a simple fix.

**Comment by shakeelmohamed** [comment]
@monicacheung done :)

**Pull request merged**
