### PR TITLE
Removed browserstack logo in index.html and README.md, closes #172

### LINKED ISSUE #172: Remove browserstack logo (new contributors only)
#### I'd like a new contributor to do this

Since we're not going to do #71 we don't need to say we're "sponsored by" browserstack.

Done criteria:

- [x] Remove the logo from `index.html`
- [ ] Make sure the design is still responsive, and the previous step didn't have any side effects
- [ ] Update the screenshot/mockup in the README

Focus on the first step, if you run into issues with the others @YuriBrunetto can help out.

### PR DESCRIPTION
**Pull request by guillermohernandez**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x ] Why is this change required? What problem does it solve?
Update required to close #172
- [x ] If it fixes an open issue, include the text `Closes #172` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ x] Describe your changes in detail.
Removed Browserstack img and link from sponsor div in index.html. Removed reference to Browserstack in README.md

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [x ] All tests passed.

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks for doing this @guillermohernandez!
Can you or @YuriBrunetto update the screenshot we have in the readme as well?

**Comment by guillermohernandez** [comment]
You're welcome. 
I updated the screenshot but its missing the glossy effect. 
If @YuriBrunetto sends me a PSD, I can update it quick and push it

**Comment by shakeelmohamed** [comment]
@guillermohernandez we have everything you need right [here](https://github.com/zen-audio-player/design-resources) :smile:

**Comment by shakeelmohamed** [comment]
Looks like we'll need some CSS tweaks as well since the design is a bit lop-sided without the third logo. Since @YuriBrunetto wrote that code... another ping for him!

capturfiles_23

**Comment by YuriBrunetto** [comment]
Hey guys! I'll fix this in a minute

**Comment by shakeelmohamed** [comment]
You rock!

**Comment by guillermohernandez** [comment]
Fixed both. Let me know if it works @YuriBrunetto

**Comment by shakeelmohamed** [comment]
@guillermohernandez screenshot will need another update with the CSS change.

@YuriBrunetto I'll merge this after you sign off, but it looks good to me pending the updated screenshot

**Comment by YuriBrunetto** [comment]
[screenshot updated!](https://github.com/zen-audio-player/zen-audio-player.github.io/pull/179l)

@guillermohernandez nice work! :+1: 
@shakeelmohamed looks good to me too

**Comment by shakeelmohamed** [comment]
Great work folks! Welcome to the org @guillermohernandez :tada:

**Pull request merged**
