### PR TITLE
Added playlist feature, without any OAuth, using localstorage

### LINKED ISSUE #229: Create A To-Be-Played and Have-Played Queue
We could add a queue, similar to that of Mixcloud (bottom bar) that shows the things one played recently or allows to queue things to be played next.

### PR DESCRIPTION
**Pull request by chandan1794**
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x] Why is this change required? What problem does it solve?
This solves the problem of searching a song again and again. A user can make there on the playlist and play at a later time, provided they don't clear their browser cache.
- [x] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.
Closes #229 : Implemented **To-Be-Played** list.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.

1. Added a button with the search button, that button will show the playlist.
2. When search, with each result, there is a button **Watch Later**, which will add the respective song to the playlist.
3. The user can see the songs later on and play.

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [ ] All tests passed.
I am not able to run `npm test` properly. Have posted the issue in Gitter chat room too.
I have tested the code on my local, by hosting the website and it worked correctly.

### CODE REVIEW

**Comment by chandan1794** [comment]
@shakeel should I re run the tests and create a new PR?

**Comment by chandan1794** [comment]
Hi @shakeelmohamed , I have made the necessary changes and passed all the test cases.

**Comment by chandan1794** [comment]
Hi @shakeelmohamed , any comments on the PR?

**Comment by shakeelmohamed** [comment]
@chandan1794 give me a few days to try it out locally, code seems generally reasonable at a glance

**Comment by chandan1794** [comment]
> @chandan1794 give me a few days to try it out locally, code seems generally reasonable at a glance

Sure 👍

**Comment by shakeelmohamed** [comment]
Closing due to inactivity

**Pull request closed without merging**
