### PR TITLE
Added reference `CONTRIBUTING.md` file at the bottom of `README.md`

### LINKED ISSUE #84: Mention contributing notes in README
Just need to add a heading and a short sentence linking to the `CONTRIBUTING.md` file

### PR DESCRIPTION
**Pull request by thomasjosephgreco**
Closes #84

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks @thomasjosephgreco!
Can we change "be sure to" --> "please" for politeness? :smirk:

**Comment by thomasjosephgreco** [comment]
@shakeelmohamed took me a little bit to re-work that as I am fairly new to using git to contribute to open-source but there you go :+1: first one in the books !

**Comment by shakeelmohamed** [comment]
Congrats @thomasjosephgreco! We love contributions of any size, welcome to the org :smiley:

**Comment by thomasjosephgreco** [comment]
thank you @shakeelmohamed

**Pull request merged**
