### PR TITLE
Fixes #39 Replay doesn't work.

### LINKED ISSUE #39: Replay doesn't work
When a video finishes, the play/pause button should return to play, then when play/pause is clicked it should restart the video.

### PR DESCRIPTION
**Pull request by BeigeBadger**
Fixes
https://github.com/zen-audio-player/zen-audio-player.github.io/issues/39

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks for making the first non-me pull request @BeigeBadger !

A couple notes:

1. Travis CI failed the build because you mixed tabs & spaces
2. You can actually replace all of your changes by calling `togglePlayPause()`, [see line 72 in everything.js](https://github.com/zen-audio-player/zen-audio-player.github.io/blob/54db94e771da84508f0a96c8984e8322627ec5f8/js/everything.js#L72)

**Comment by BeigeBadger** [comment]
Hi @shakeelmohamed!

Sorry about the mixed tabs and spaces - I am a bad man, that'll teach me to use notepad for what I thought was a quick change. 

As for using togglePlayPause() I remember thinking about using it but discounting it for some reason. 

I will make the above changes and resubmit my pull request. 😆

**Comment by shakeelmohamed** [comment]
Actually, we shouldn't use `togglePlayPause()` since that will play/pause the video also. Ideally we refactor `togglePlayPause()` to use a helper function which just does the following:

```javascript
$("#play").toggle();
$("#pause").toggle();
```

**Comment by BeigeBadger** [comment]
Ok I've fixed up errors, we should be good to go!

**Comment by shakeelmohamed** [comment]
Awesome, thanks again for doing this! Shoot me an email, I'm curious about your how you're using this :+1:

**Comment by BeigeBadger** [comment]
No worries @shakeelmohamed. I'm actually doing this as part of https://hacktoberfest.digitalocean.com/ (yay for free tee shirts!) I'm a dotNET developer by trade but I do use some jQuery and vanilla JS in my job as well.

I find JS problems much easier to tackle as usually then can be isolated to a small section of the source code without the need to setup a huge dev environment or have an intimate understanding of how the application functions in the minutae.

It also seems that JS frameworks are taking over web applications, so before I become obsolete I thought I'd better start learning. ;-) I'll pop in some subs and potential features to the wiki (if I can) then go from there.

**Comment by shakeelmohamed** [comment]
Oh sweet, I'm going to join that! I'm in the process of setting up a Slack room, if you're interested I can work on that sooner

**Pull request merged**
