### PR TITLE
Closes #93 - Update to contributing guide

### LINKED ISSUE #93: Update contributing notes to mention "Add Closes #<issue number>" to commit or PR text (putting in the title doesn't help)
By adding something like `Closes #1` to a commit or PR description, when the PR is merged that issue will automatically be closed.
This small thing helps saved some housekeeping work afterwards :smile: 

See GitHub's blog post about this feature for more info: https://github.com/blog/1386-closing-issues-via-commit-messages

Very rough text might be something like: 
- [ ] "Add Closes #<issue number> to a commit or pull request description when addressing an existing issue"
- [ ] "After you've had 1 PR merged, @shakeelmohamed should add you to the organization. Then you can create any issues you work on before you start. Leave a comment when you've started working on an issue, doing so helps avoid duplicate work."

### PR DESCRIPTION
**Pull request by joshghent**
Updated contributing guide to include information on closing issues with commits.

### CODE REVIEW

**Comment by joshghent** [comment]
Also removed a trailing line at the end of the document.

**Comment by shakeelmohamed** [comment]
TODO, either here or in another PR:

- [ ] Add steps for resolving out of sync branches
- [ ] After you've had 1 PR merged, @shakeelmohamed should add you to the organization. Then you can create any issues you work on before you start. Leave a comment when you've started working on an issue, doing so helps avoid duplicate work."

**Comment by shakeelmohamed** [comment]
ping @joshghent

**Comment by joshghent** [comment]
Done, not had much time for this project, sorry! Still working on integrating plyr.

**Comment by shakeelmohamed** [comment]
Thanks!

**Pull request merged**
