### PR TITLE
Update screenshot #167

### PR DESCRIPTION
**Pull request by YuriBrunetto**
@shakeelmohamed what do you think?

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
I like the gradient design in the background, but I think showing a phone is a bit misleading since it doesn't really work on iOS.

**Comment by YuriBrunetto** [comment]
@shakeelmohamed hmm.. so, do I remove the iPhone?

**Comment by shakeelmohamed** [comment]
@YuriBrunetto I think so. We might consider making an iOS app, but I don't know if that's even a reasonable project since you can play YouTube videos while using other apps

**Comment by YuriBrunetto** [comment]
@shakeelmohamed what about now? :smile:

**Comment by shakeelmohamed** [comment]
I like it! Before I merge it, do you have a template or project file for the image? If so, I can make a new repo called "design resources" and you can check it in there. The goal is to make updating the screenshot possible for anyone

**Comment by YuriBrunetto** [comment]
Yes, I have the .psd here!

**Comment by shakeelmohamed** [comment]
@YuriBrunetto see https://github.com/zen-audio-player/design-resources/issues/1

**Pull request merged**
