### PR TITLE
Updated screenshot, closes #197

### LINKED ISSUE #197: Update the screenshot - plyr support
I keep forgetting to do this every time the UI changes 😅 

See #177 for how this works.

cc: @guillermohernandez @YuriBrunetto you folks want to do this since you've done it before ❓

### PR DESCRIPTION
**Pull request by guillermohernandez**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [x] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [ ] All tests passed.

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Let's resolve the merge conflicts first (which should be nothing....) click the `command line instructions` link above and that will walk you through it.

After the conflicts are resolved, click the demo link and skip to about halfway through the song and then take a screenshot. That should be a lot more valuable that just a screenshot of the home page 😄

**Comment by guillermohernandez** [comment]
Looks like it will be a while before I can update it. Having licensing issues with Adobe Creative Cloud but a ticket has been created for my IT department

**Comment by shakeelmohamed** [comment]
@guillermohernandez any progress? You might be able to use [gimp](http://www.gimp.org/) to do this if you don't have access to Photoshop

**Comment by guillermohernandez** [comment]
@shakeelmohamed installing gimp now. I apologize for the lack of updates. Started a new job. Dev only; no design

**Comment by guillermohernandez** [comment]
@shakeelmohamed I don't know my way around gimp well enough to make this happen. It's a shame cause I had a good screenshot of the glitch mod demo. Maybe @YuriBrunetto can help me out

**Comment by shakeelmohamed** [comment]
@guillermohernandez neither do I, no worries 😆

**Comment by YuriBrunetto** [comment]
hey guys! what's the problem?

**Comment by guillermohernandez** [comment]
@YuriBrunetto no license to Adobe CC now and don't know Gimp well enough to edit the screenshot. Can you please update the screenshot so we can close this?

**Comment by YuriBrunetto** [comment]
@guillermohernandez there ya go :smile: https://github.com/zen-audio-player/zen-audio-player.github.io/pull/205

**Comment by shakeelmohamed** [comment]
Closing as dupe

**Pull request closed without merging**
