### PR TITLE
Aligned Logo without adding any new classes and making changes to existing ones

### PR DESCRIPTION
**Pull request by MisterAwesome23**

### CODE REVIEW

**Comment by MisterAwesome23** [comment]
Note: On the new branch I have not used magic numbers nor any new css class. And to be more detailed the new branch will be more suitable for designing when new sponsor is to be added because I've made it modular.

**Comment by shakeelmohamed** [comment]
Great work @MisterAwesome23, thanks for sticking with it and working with my feedback!

**Comment by MisterAwesome23** [comment]
Did I just get my first merge? Boy it feels good :))
Thank you so much for patience and you sticking with me. Please let me know more areas to work on. Thank you.

**Comment by shakeelmohamed** [comment]
@MisterAwesome23 Yes!!! I've pinged you on another ticket

**Pull request merged**
