### PR TITLE
Closes #110 Implementation of URI library

### LINKED ISSUE #100: Replace html5-lint dependency
See #98. The server html5-lint was using has been shut down, so we need to find another way to do HTML validation for the tests.
I am very open to suggestions here!

### LINKED ISSUE #110: Simplify all URL parsing code with URI.js
This seems like a good library and not too large of a dependency, what do we think? https://github.com/medialize/URI.js

### PR DESCRIPTION
**Pull request by rjstires**
Per Issue #100 request to implement URI.js throughout JS codebase for uniform parsing and manipulation of URIs. I chose to open this with URI.js as the other proposed library did not have mutation ability.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [X] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.
- `parseYoutubeVideoID()` was updated to make use of URI.js both parsing and manipulation. I would like an example of slashes in the URI so that I might provide a better solution. (refer to TODO on `zap-common.js#74`)
- `isFileProtocol()` and `anonymizeFileUrl()` have been simplified by making use of the URI.js library.
- `getCurrentVideoID()` also makes use of the library. There was no the function wasn't self documenting and was vague in it's purpose. It seemed that it was ultimately attempting to locate the v query parameter, and if there were multiple, return the last value. This is how the function operates now.

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [ ] All tests passed.

*Note*: Tests never passed on the initial clone of the repo. On initial local run there were a number of console errors, but the software functioned as expected both before and after modification.

**Looking forward to feedback**

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks @rjstires, first off you'll need to install the URI.js lib and check in the bower components (make sure `bower.json` gets updated too): `bower install --save uri.js `. If you merge the `master` branch to your fork's `master` branch all tests will pass, but functionality is definitely broken from your changes

**Comment by rjstires** [comment]
@shakeelmohamed having forked your project, only this morning, any idea why the tests failed?

**Comment by shakeelmohamed** [comment]
@rjstires yeah, basically URI.js wasn't loading (since it wasn't checked in) and 404s cause some tests to fail

**Comment by rjstires** [comment]
Got it, Ill get it up and running. I'm unfamiliar with Bower, been a die hard NPM fan.

**Comment by shakeelmohamed** [comment]
@rjstires they're not mutually exclusive 😂

**Comment by rjstires** [comment]
Sorry for the headaches >.<

**Comment by shakeelmohamed** [comment]
Leaving a comment for others... @rjstires & I found that these changes, so far, broke the website's functionality

**Comment by shakeelmohamed** [comment]
@rjstires I'm curious if your changes here (once working) will fix #225

**Comment by rjstires** [comment]
It would, yes. Ill try to sneak some time away from the wife this weekend and get this closed.

**Comment by rjstires** [comment]
See https://github.com/zen-audio-player/zen-audio-player.github.io/pull/226

**Pull request closed without merging**
