### PR TITLE
Moved content from Contributing, Pull Request and Issue markdown files to Making Contributions wiki page. Moved Contact information to Readme.md. Closes first task of issue #201.

### PR DESCRIPTION
**Pull request by Kelby-Baca**
This pull request is to solve the first task in issue #201 (and to make the Issue and PR pages a bit less verbose.)

I moved everything in the CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, and the ISSUE_TEMPLATE.md to the Making Contributions page on the wiki. I also edited any links to CONTRIBUTING.md to point to the Making Contributions page. I also moved the Gitter Contact information from the top of CONTRIBUTING.md to the bottom of the README.md file.

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
@Kelby-Baca thank you for this! I super appreciate the effort

Instead of creating a `wiki` directory, let's just add the content to the wiki for this repo (you should have edit access, let me know if you don't): https://github.com/zen-audio-player/zen-audio-player.github.io/wiki

The files in the `.github` are used by the GitHub UI, so I think we should keep them - let's just keep the summary of content:
* When `contributing.md` is present, it shows a yellow bar with a link to that file. I think keeping the gitter badge is a must.
* The issue & PR templates are used to pre-fill the form when creating a new issue or pull request. (**I think these 2 file have too much information and are a bit cumbersome**)

**Comment by Kelby-Baca** [comment]
@shakeelmohamed You're welcome! I also didn't realize you could edit the wiki pages directly on the repo. I DO have write access - I just clicked the "Edit" button on one of the pages and it didn't stop me.

I'll put all the .github files back the way they were, and make them as concise as possible. Thanks for the feedback!

**Comment by shakeelmohamed** [comment]
@Kelby-Baca Great, let me know when you're ready for another review

**Comment by Kelby-Baca** [comment]
@shakeelmohamed Hi there, I'm almost ready for another review. I just needed to clarify something - would you rather keep the entirety of contributing.md like it is now? Or do you need me to trim that file down as well, and maybe move some of it to the wiki pages?

**Comment by shakeelmohamed** [comment]
@Kelby-Baca let's keep contributing.md as is, but trim the PR and issue templates

**Comment by Kelby-Baca** [comment]
@shakeelmohamed Okay, great!

**Comment by shakeelmohamed** [comment]
@divayprakash contributing.md needs to come back before merging this one

**Comment by shakeelmohamed** [comment]
Closing due to inactivity

**Pull request closed without merging**
