### PR TITLE
updated the Logo

### PR DESCRIPTION
**Pull request by IsaiahN**
updated logo

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Great, can we get `zen-audio-player-453.png` to be less pixelated along the diagonal? And also update `zen-audio-player-905.png`

Thanks!

**Comment by IsaiahN** [comment]
It's been changed

**Comment by shakeelmohamed** [comment]
Awesome, thank you!!!

**Comment by IsaiahN** [comment]
Thank you for the spacejam throwback :+1: :smile:

**Pull request merged**
