### PR TITLE
Update primer (#189)

### PR DESCRIPTION
**Pull request by akkatracker**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [x] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message. 

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

If you could call it a bug, keeping dependencies up to date (general cleanup)

### Description
- [x] Describe your changes in detail.
Update the version of primer used.
**Before**
before
**After**
after

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [x] All tests passed.
Signed-off-by: Matthew Brener <mdbrener@bigpond.net.au>

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks @akkatracker, can you also check in the updated bower_components directory?

**Comment by akkatracker** [comment]
Sure I'll commit it tonight

**Comment by akkatracker** [comment]
Added :+1: 

Thanks for the experience - this is helping me pick up git and js quite nicely :)

**Comment by shakeelmohamed** [comment]
Ship it! Thanks @akkatracker, welcome to the org.

**Pull request merged**
