### PR TITLE
Closes #223 add thumbnails as their own list item after search

### LINKED ISSUE #223: Add Thumbnails to List Returned After Search
It seems to me that this would make the app more friendly to the eye. Often, I would like to re-listen to same videos or mixes. I generally recognize them by their thumbnails. 

I could probably implement this feature (just starred your repo, so it may take me some time to get familiar).

### PR DESCRIPTION
**Pull request by jacondel**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [ ] All tests passed.

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Thanks @jacondel, we'll need to address a few things before merging.

- [ ] We should put the thumbnail all within 1 `<li>`, this is standard HTML convention
- [ ] Create a CSS class in `styles.css` for these list items, maybe `.search-result-item`, and add the  following styles there

```css
vertial-align: middle;
margin-right: 10px;
```
- [ ] Update the `start` variable to use the `.search-result-item` class
- [ ] Add `result.snippet.title` as the `alt` attribute for the thumbnail `` tag

**Comment by jacondel** [comment]
I added the CSS class `.search-result-item`, added the `alt` attribute, and made the thumbnail clickable as well. I didn't do anything with the size of the thumbnail but it looks reasonable to me.

**Comment by shakeelmohamed** [comment]
I thought about this again. Since you've still got the thumbnail under the title, just remove the new `.search-result-item` rule and the usage in `everything.js`

**Comment by shakeelmohamed** [comment]
Thanks @jacondel!

**Pull request merged**
