### PR TITLE
Rework - adding soundcloud support

### LINKED ISSUE #2: Add support for Soundcloud
I've been thinking about how we can implement Soundcloud support as seamlessly as possible. @monicacheung did a ton of great work in getting this process started, but I think the next step is **breaking out Soundcloud support into it's own repo**.
- I've created a new repo: [zen-audio-player/soundcloud](https://github.com/zen-audio-player/soundcloud)
- The beauty of GitHub Pages allows us to have the url https://ZenPlayer.audio/soundcloud, which now has a holding page
- With a dedicated repo, we can create separate JS files for working Soundcloud without worrying about clobbering the YouTube code. (I'm mainly concerned with the hackiness of `wrapParseVideoID()` in `zap-common.js`)
- In this repo, under the search box we can add a set of radio buttons to determine where to route the request (ie: default to YouTube, and have Soundcloud as an option).
- Breaking things out like this will make adding support for other services easier.

---

Options for both playlists, and single tracks would be cool.
- [x] Figure out how to use the soundcloud JS widget API
- [x] Figure out how to dynamically change the soundcloud track
- [x] Add support to the searchbox for a soundcloud URL
- [x] Update `parseYoutubeVideoID()` to have an else if condition for soundcloud URLS
- [x] Rename `parseYoutubeVideoID()` to something more generic, and updated all uses of the function.
- [x] Add support for pulling a soundcloud URL from the URL, ie: `https://zen-audio-player.github.io/?v=https%3A%2F%2Fsoundcloud.com%2Fuser%2Ftrack`)
- [x] Figure out how to hide the player
- [x] Figure out how to hook into the play/pause controls
- [x] Figure out how to hook into the volume controls
- [ ] Set a "mode" for YouTube vs. soundcloud to prevent the play/pause/volume/show/hide controls from affecting the wrong player
- [ ] Test it out on a few browsers

### PR DESCRIPTION
**Pull request by shakeelmohamed**
Closes #2, replaces #186

You can enter a Soundcloud URL/trackID in the search bar or as a query string (?v=) in the URL and ZAP will play it.

**Try these out in the ZAP search bar or ?v= in the URL:**
- https://soundcloud.com/theglitchmob/starve-the-ego-feed-the-soul
- https://api.soundcloud.com/tracks/3096795
- 3096795

**Todo/Things that broke:**
- [ ] Fix the tweet message.
- [ ] functionality is generally broken
- [ ] handle 403 from protected tracks (not sure if this is because they're protected tracks, because accessing the URL over cURL works just fine)
- [ ] Fix storing current time of player and resume on returning to page.
- [ ] Update the UI a bit to be indicative of soundcloud support.
- [ ] More TODO in the code.
- [ ] Consider breaking up the soundcloud specific loging into a seperate `soundcloud.js` file
- [x] fix merge conflicts against master

### CODE REVIEW

**Comment by dasbishnu** [comment]
Hi, I might be able to help fixing a few bugs (#beginner-level). Not sure which of the ones are already fixed by you. The tweet message seems to be fixed in production. Let me know which one to work. BTW sound cloud support will up the players usage :)

**Comment by shakeelmohamed** [comment]
@dasbishnu thanks! None of the checkbox items the description of this PR are done on this branch. When you fork, you should work from the `feature/soundcloud` branch

**Comment by dasbishnu** [comment]
Cool then 'll start working on the feature branch

**Comment by shakeelmohamed** [comment]
@dasbishnu cool, don't worry about the merge conflicts. I will take care of them eventually

**Comment by shakeelmohamed** [comment]
@dasbishnu any updates? I'm opening this back up to anyone, I'd love to get this in for Hacktoberfest

**Comment by dasbishnu** [comment]
Hi Shakeel,

Apologies for the delay. In case you have still not opened, I'll work on this bug and close this by this weekend.

Bishnu
Sent from Outlook Mobile<https://aka.ms/blhgte>



On Mon, Oct 3, 2016 at 10:37 AM +0530, "Shakeel Mohamed" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dasbishnu<https://github.com/dasbishnu> any updates? I'm opening this back up to anyone, I'd love to get this in for Hacktoberfest

-

**Comment by shakeelmohamed** [comment]
@dasbishnu no worries. Please read my update to the description of #2

**Comment by dasbishnu** [comment]
Ok

Bishnu
Sent from Outlook Mobile<https://aka.ms/blhgte>



On Sun, Oct 9, 2016 at 4:25 AM +0530, "Shakeel Mohamed" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dasbishnu<https://github.com/dasbishnu> no worries. Please read my update to the description of #2<https://github.com/zen-audio-player/zen-audio-player.github.io/issues/2>

-

**Comment by dasbishnu** [comment]
Hi Shakeel,

Got preoccupied with office work this weekend. I'll take up some other bug later. Pls release this bug from my name. Apologies, will surely take up another bug.

Bishnu
Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by shakeelmohamed** [comment]
@dasbishnu Sure thing, don't worry about it! I actually need to do some groundwork on refactoring everything into the new repo anyways 😄

**Comment by sheamunion** [comment]
@shakeelmohamed I'd love to help out on this issue. Is the plan still to work through the TODO list in the description?

**Comment by shakeelmohamed** [comment]
@sheamunion yeah, although the tough part will be resolving the merge conflicts against master.

**Comment by shakeelmohamed** [comment]
Closing as won't fix

**Pull request closed without merging**
