### PR TITLE
Adding Twitter Cards, closes #178

### LINKED ISSUE #178: Add support for Twitter Cards
It would be really nice to show something (not the thumbnail obviously) in a Twitter card when a https://zenplayer.audio link is shared. Can we show the actual player, something like soundcloud? ([example](https://twitter.com/davidguetta/status/522843748066013185))

Need to brainstorm this a bit, but the [docs for Twitter cards are here](https://dev.twitter.com/cards/overview).

### PR DESCRIPTION
**Pull request by divayprakash**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [x] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail - Adding support for Twitter Cards

### Final checklist:
Go over all the following points and check all the boxes that apply  
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](.github/CONTRIBUTING.md) guidelines.
- [ ] All tests passed.

### CODE REVIEW

**Comment by divayprakash** [comment]
@shakeelmohamed Have a look, the Code Climate issues are all duplication bugs due to same code in `everything.js` and `iframe.js`. This is my first time working with JS so I'm pretty much shooting in the dark here!

**Comment by shakeelmohamed** [comment]
@divayprakash no worries, you can safely ignore the Code Climate warnings for now 😄  I'll help refactor before we merge your changes in.

I'd suggest 2 things though creating a `gh-pages` branch in your forked repo, so you can use the [Twitter card validator](https://cards-dev.twitter.com/validator) to get some  feedback. Once you have a `gh-pages` branch, https://divayprakash.github.io/zen-audio-player.github.io should become a valid URL.

**Comment by divayprakash** [comment]
@shakeelmohamed Done some more work. Also I've created the `gh-pages` branch on my fork of this repo for testing. It's currently up to date with the branch of this PR ie. `divayprakash/twitter-cards`. The Twitter Card Validator is still unable to render a preview so I'm guessing there is some error in the `meta` tags in `index.html` namely the `twitter:player` tag, so please check that out.

**Comment by shakeelmohamed** [comment]
@divayprakash It looks like domains have to be manually whitelisted for player cards. I've requested your fork to be whitelisted for now using my Twitter account `https://divayprakash.github.io/zen-audio-player.github.io/`. Eventually that will be updated to the real URL

**Comment by shakeelmohamed** [comment]
@divayprakash your github pages domain is now whitelisted for Twitter cards. Something isn't right according to the validator, but I'm not sure what exactly

**Comment by shakeelmohamed** [comment]
@divayprakash what's the status here?

**Comment by divayprakash** [comment]
@shakeelmohamed Sorry for the delay but I'm just swamped with work right
now. I will surely get back to this but just a little later.

**Comment by divayprakash** [comment]
@shakeelmohamed I've tried this again but it just doesn't seem to be working, maybe you could take a look? I can't figure out what is going wrong here.

**Comment by shakeelmohamed** [comment]
@divayprakash sure I'll see what I can do 😄

**Comment by shakeelmohamed** [comment]
@divayprakash I have it working just fine with the twitter validator using `https://zenplayer.audio/test/` as the test URL. You can manually test the iframe [here](https://zenplayer.audio/test/iframe.html?v=koJv-j1usoI).

Here's the problem, the `<meta>` tag for `twitter:player` needs to contain the video ID, ie: `koJv-j1usoI` when the page loads. However, `<meta>` tags must be set before any JavaScript code runs (they can be changed but, the changes essentially have no effect for Twitter cards). We're unable to parse the video ID from the URL without JavaScript... so we're in a bit of a "deadlock" situation here. The real solution would be use a server-side language to generate the `<meta>` tag - but that means we can't use GitHub pages and we'd likely have to pay to host the website.

Any ideas? 😅

**Comment by divayprakash** [comment]
I stumbled on this same problem, but didn't know how to get past it without
a server-side language to generate the `<meta>` tag. I thought maybe
there's a way around it which you'd know better.

**Comment by divayprakash** [comment]
I stumbled on this same problem, but didn't know how to get past it without a server-side language to generate the `<meta>` tag. I thought maybe there's a way around it which you'd know better.

**Comment by shakeelmohamed** [comment]
Ok, I'm going to close this PR once I move my changes to the `test repo to a branch on this repo.

Thanks again for all your effort here, but unless Twitter changes something this might not be possible unfortunately

**Comment by divayprakash** [comment]
@shakeelmohamed Confirmation of the same, we cannot implement this in the present implementation of twitter cards : https://twittercommunity.com/t/dynamically-adding-meta-tags-using-javascript-or-jquery-twitter-cards/22896

**Comment by shakeelmohamed** [comment]
@divayprakash yup, going to close as impossible for now 😦

**Pull request closed without merging**
